version: '3'
services:
  nginx:
        build: ./requirements/nginx
        container_name: nginx
        image: "nginx"
        restart: always
        depends_on:
          - wordpress
        ports:
          - "443:443"
        volumes:
          - /data/html:/var/www/html
  wordpress:
        build: ./requirements/wordpress
        container_name: wordpress
        restart: always
        volumes:
          - /data/html:/var/www/html
        networks:
          - inception_network
 
networks:
  inception_network:
    driver: bridge