version: '3'

services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - /home/inception-selfcht/data/html:/var/www/html
    networks:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - /home/inception-selfcht/data/html:/var/www/html
    networks:
      - wordpress
    env_file:
      - .env
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - 3306:3306
    volumes:
      - /home/inception-selfcht/data/mysql:/var/lib/mysql
  

networks:
  wordpress:
    driver: bridge
