version: '3'

services:
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - "3306:3306"
    volumes:
      - DB:/var/lib/mysql
  nginx:
    depends_on: 
      - wordpress
    build: ./requirements/nginx
    image: nginx 
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - Wordpress:/var/www/html
      - phpmyadmin:/var/www/html/phpmyadmin
      - adminer:/var/www/html/adminer
      - showcase:/var/www/html/showcase
    networks:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - Wordpress:/var/www/html
      - phpmyadmin:/var/www/html/phpmyadmin
      - adminer:/var/www/html/adminer
      - showcase:/var/www/html/showcase
    ports: 
      - "9000"
    networks:
      - wordpress
    env_file:
      - .env
  phpmyadmin:
    build: ./requirements/bonus/phpmyadmin
    depends_on:
        - nginx
    restart: unless-stopped
    volumes:
      - phpmyadmin:/usr/share/phpmyadmin
    networks: 
      - wordpress
    container_name: "phpmyadmin"
    image: "phpmyadmin"
  adminer:
      build: ./requirements/bonus/adminer
      depends_on: 
        - nginx
      image: adminer
      container_name: adminer
      restart: unless-stopped
      volumes:
        - adminer:/usr/share/adminer/adminer
      networks: 
        - wordpress
  showcase:
      build: ./requirements/bonus/showcase
      depends_on:
        - nginx
      image: showcase
      container_name: showcase
      restart: always
      volumes:
        - showcase:/var/www/html/showcase
      networks: 
        - wordpress
      ports: 
        - "7777:7777"
  redis:
      build: ./requirements/bonus/redis
      depends_on: 
        - nginx
      image: redis
      container_name: redis
      restart: always
      ports: 
        - 6379:6379
      networks: 
        - wordpress
      env_file: 
        - .env
  ftps:
      env_file: 
        - .env
      build: 
        context: ./requirements/bonus/ftps
        args:
              FTP_USER: ftpuser
              FTP_PASSWORD: password
      container_name: ftps
      image: ftps
      networks: 
        - wordpress
      volumes:
        - Wordpress:/var/www/html/
      ports: 
        - "20:20"
        - "21:21"
        - "1024-1048:1024-1048"
volumes:
  Wordpress:
    driver_opts:
      type: none
      device: /home/souhail/data/Wordpress
      o: bind
  DB:
    driver_opts: 
      type: none
      device: /home/souhail/data/DB
      o: bind
  phpmyadmin:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: 'home/souhail/data/phpmyadmin'
  adminer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/souhail/data/adminer'
  showcase:
    driver: local
    driver_opts: 
      type: 'none'
      o: 'bind'
      device: '/home/souhail/data/showcase'

networks:
  wordpress:
    driver: bridge
        