version: '3'

services:
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - "3306:3306"
    volumes:
      - DB:/var/lib/mysql
  nginx:
    depends_on: 
      - wordpress
    build: ./requirements/nginx
    image: nginx 
    container_name: nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - Wordpress:/var/www/html
     # - phpmyadmin:/var/www/html/phpmyadmin
      - adminer:/var/www/html/adminer
    networks:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - Wordpress:/var/www/html
      #- phpmyadmin:/var/www/html/phpmyadmin
      - adminer:/var/www/html/adminer
    ports: 
      - "9000"
    networks:
      - wordpress
    env_file:
      - .env
#  phpmyadmin:
#     build: ./requirements/bonus/phpmyadmin
#     restart: on-failure
#     volumes:
#       - phpmyadmin:/usr/share/phpmyadmin
#     networks: 
#       - wordpress
#     container_name: "phpmyadmin"
#     image: "phpmyadmin"
  adminer:
      build: ./requirements/bonus/adminer
      depends_on: 
        - nginx
      image: adminer
      container_name: adminer
      restart: unless-stopped
      volumes:
        - adminer:/usr/share/adminer/adminer
      networks: 
        - wordpress

volumes:
  Wordpress:
    driver_opts:
      type: none
      device: /home/souhail/data/Wordpress
      o: bind
  DB:
    driver_opts: 
      type: none
      device: /home/souhail/data/DB
      o: bind
 # phpmyadmin:
  #  driver: local
   # driver_opts: 
    #  type: 'none'
     # o: 'bind'
      #device: 'home/souhail/data/phpmyadmin'
  adminer:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/souhail/data/adminer'

networks:
  wordpress:
    driver: bridge
        