version: '3'

services:
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    image: "mariadb"
    restart: always
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql/

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: "wordpress"
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress
    env_file:
      - .env

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    image: "nginx"
    ports:
      - 443:443
    volumes:
      - wordpress:/var/www/html
    networks:
      - wordpress



networks:
  wordpress:
    driver: bridge
  
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/inception-selfcht/data/mariadb'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/inception-selfcht/data/wordpress'
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/inception-selfcht/data/nginx'

