version: '3'

services:
    mariadb:
        build: ./requirements/mariadb
        image: mariadb
        container_name: mariadb
        restart: always
        env_file: .env
        ports:
          - "3306"
        environment:
          DOMAINE_NAME: sel-fcht.1337.ma
          WP_DB_NAME: wordpress_db
          WP_DB_USER: selfcht
          WP_DB_PASS: souhail01          
        volumes:
          - dbdata:/var/lib/mysql
        command: '--default-authentication-plugin=mysql_native_password'
        networks:
          - inception_network
    wordpress:
        build: ./requirements/wordpress
        image: wordpress
        container_name: wordpress
        ports:
          - "9000"
        depends_on:
          - mariadb
        restart: always
        env_file: .env
        environment:
          - WORDPRESS_DB_HOST=db:3306
          - WORDPRESS_DB_USER=$MYSQL_USER
          - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
          - WORDPRESS_DB_NAME= wordpress_db
        volumes:
          - wordpress:/var/www/html
        networks:
          - inception_network
    nginx:
        build: ./requirements/nginx
        container_name: nginx
        depends_on:
          - wordpress
        image: nginx
        restart: always
        ports:
          - "8080:80"
          - "443:443"
        volumes:
          - wordpress:/var/www/html
          - ./nginx-conf:/etc/nginx/conf.d
        networks:
          - inception_network
        environement:
          - NGINX_HOST: test.com
          - NGINX_PORT: 80
    certbot:
        depends_on:
          - webserver
        image: certbot/certbot
        container_name: certbot
        volumes:
          - certbot-etc:/etc/letsencrypt
          - wordpress:/var/www/html
        command: certonly --webroot --webroot-path=/var/www/html --email sel-fcht@student.1337.ma --agree-tos --no-eff-email --staging -d www.sel-fcht.com -d www.sel-fcht.com
    phpmyadmin:
        image: corbinu/docker-phpmyadmin
        links:
          - mariadb:mysql
        ports:
          - 8181:80
        environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: souhail01
networks:
      inception_network:
      driver: bridge