version: '3'

services:
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - 3306:3306
    volumes:
      - /home/sel-fcht/data/mysql:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - /home/sel-fcht/data/html:/var/www/html
    networks:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/sel-fcht/data/html:/var/www/html
    networks:
      - wordpress
    env_file:
      - .env

networks:
  wordpress:
    driver: bridge
  
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sel-fcht/data/mysql'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sel-fcht/data/html'
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sel-fcht/data/html'       

