version: '3'

services:
  mariadb:
    build : ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    networks:
      - wordpress
    ports:
      - 3306:3306
    volumes:
      - /home/sel-fcht/data/mysql:/var/lib/mysql
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - 443:443
    volumes:
      - /home/sel-fcht/data/html:/var/www/html
      - adminer:/var/www/html/adminer
      - phpmyadmin:/var/www/html/phpmyadmin
    networks:
      - wordpress

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
    volumes:
      - /home/sel-fcht/data/html:/var/www/html
      - adminer:/var/www/html/adminer
      - phpmyadmin:/var/www/html/phpmyadmin
    networks:
      - wordpress
    env_file:
      - .env
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: on-failure
    networks:
      - wordpress
    volumes:
      - adminer:/usr/share/adminer/adminer
  phpmyadmin:
    build: ./requirements/bonus/phpmyadmin
    container_name: phpmyadmin
    restart: always
    volumes: 
      - phpmyadmin:/usr/share/phpmyadmin
    networks: 
      - wordpress
    image : phpmyadmin
networks:
  wordpress:
    driver: bridge
  
volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sel-fcht/data/mysql'
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sel-fcht/data/html'
  nginx:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/sel-fcht/data/html' 
  adminer:
      driver: local
      driver_opts:
        type: 'none' 
        o: 'bind'   
        device: '/home/sel-fcht/data/adminer'   
  phpmyadmin:
      driver: local
      driver_opts: 
        type: 'none'
        o: 'bind'
        device: 'home/sel-fcht/data/phpmyadmin'
